/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as CompareRouteImport } from './routes/compare'
import { Route as FundsRouteImport } from './routes/funds'
import { Route as RecommendRouteImport } from './routes/recommend'
import { Route as SchemesRouteImport } from './routes/schemes'
import { Route as FundsIndexRouteImport } from './routes/funds.index'
import { Route as FundsIdRouteImport } from './routes/funds.$id'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const CompareRoute = CompareRouteImport.update({
  id: '/compare',
  path: '/compare',
  getParentRoute: () => rootRouteImport,
} as any)
const FundsRoute = FundsRouteImport.update({
  id: '/funds',
  path: '/funds',
  getParentRoute: () => rootRouteImport,
} as any)
const RecommendRoute = RecommendRouteImport.update({
  id: '/recommend',
  path: '/recommend',
  getParentRoute: () => rootRouteImport,
} as any)
const SchemesRoute = SchemesRouteImport.update({
  id: '/schemes',
  path: '/schemes',
  getParentRoute: () => rootRouteImport,
} as any)
const FundsIndexRoute = FundsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => FundsRoute,
} as any)
const FundsIdRoute = FundsIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => FundsRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/compare': typeof CompareRoute
  '/funds': typeof FundsRouteWithChildren
  '/recommend': typeof RecommendRoute
  '/schemes': typeof SchemesRoute
  '/funds/$id': typeof FundsIdRoute
  '/funds/': typeof FundsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/compare': typeof CompareRoute
  '/recommend': typeof RecommendRoute
  '/schemes': typeof SchemesRoute
  '/funds/$id': typeof FundsIdRoute
  '/funds': typeof FundsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/compare': typeof CompareRoute
  '/funds': typeof FundsRouteWithChildren
  '/recommend': typeof RecommendRoute
  '/schemes': typeof SchemesRoute
  '/funds/$id': typeof FundsIdRoute
  '/funds/': typeof FundsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/compare'
    | '/funds'
    | '/recommend'
    | '/schemes'
    | '/funds/$id'
    | '/funds/'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/compare' | '/recommend' | '/schemes' | '/funds/$id' | '/funds'
  id:
    | '__root__'
    | '/'
    | '/compare'
    | '/funds'
    | '/recommend'
    | '/schemes'
    | '/funds/$id'
    | '/funds/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  CompareRoute: typeof CompareRoute
  FundsRoute: typeof FundsRouteWithChildren
  RecommendRoute: typeof RecommendRoute
  SchemesRoute: typeof SchemesRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/compare': {
      id: '/compare'
      path: '/compare'
      fullPath: '/compare'
      preLoaderRoute: typeof CompareRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/funds': {
      id: '/funds'
      path: '/funds'
      fullPath: '/funds'
      preLoaderRoute: typeof FundsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/recommend': {
      id: '/recommend'
      path: '/recommend'
      fullPath: '/recommend'
      preLoaderRoute: typeof RecommendRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/schemes': {
      id: '/schemes'
      path: '/schemes'
      fullPath: '/schemes'
      preLoaderRoute: typeof SchemesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/funds/': {
      id: '/funds/'
      path: '/'
      fullPath: '/funds/'
      preLoaderRoute: typeof FundsIndexRouteImport
      parentRoute: typeof FundsRoute
    }
    '/funds/$id': {
      id: '/funds/$id'
      path: '/$id'
      fullPath: '/funds/$id'
      preLoaderRoute: typeof FundsIdRouteImport
      parentRoute: typeof FundsRoute
    }
  }
}

interface FundsRouteChildren {
  FundsIdRoute: typeof FundsIdRoute
  FundsIndexRoute: typeof FundsIndexRoute
}

const FundsRouteChildren: FundsRouteChildren = {
  FundsIdRoute: FundsIdRoute,
  FundsIndexRoute: FundsIndexRoute,
}

const FundsRouteWithChildren = FundsRoute._addFileChildren(FundsRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  CompareRoute: CompareRoute,
  FundsRoute: FundsRouteWithChildren,
  RecommendRoute: RecommendRoute,
  SchemesRoute: SchemesRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
